# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1f671da15d06c90c7a8ec77e38d89c27641575381218523526047db1ba783d87dd0c14603d624203fde598a73b8d36e29d4944745bab1764ba429f5979d074

test:
  secret_key_base: 1f2c93d51d7fc1d8e83298c9b51b3cb6e4db998feaa760db73f190776d71107cb12f843724928293f1293d0796edfa66b09823e2f4cb60b9a23e11d4b7c3cd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
